blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/SYSFACOrder/R4EX003/issues/new?template=custom.md&projects=SYSFACOrder%2FR4EX003%2F1&labels=ToDo
