blank_issues_enabled: true
contact_links:
  - name: 新しい案件を追加する
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: echo "https://github.com/SYSFACOrder/$DAY_OF_WEEK/issues/new?template=custom.md&projects=SYSFACOrder%2Fprojects%2F3%2F1&labels=ToDo"
